export const rawFieldStaff: Array<[
  string, // Category ID (e.g. 'TC', 'TF', 'WT', 'SEC', 'TECH', 'CL', 'CM')
  string, // S/N
  string, // Full Name
  string, // DOB
  string, // Gender
  string, // State of Origin
  string, // Qualification
  string, // Location
  string, // Role/Status
  string, // DOE
  string, // Renewal
  string  // Remark/Other
]> = [
  // ================= TOLL COLLECTORS =================
  ["TC", "1", "ICHABA RUTH", "1-Dec-89", "F", "KOGI", "", "GUDU", "TOLL COLLECTOR", "15-Oct-11", "", ""],
  ["TC", "2", "BILKISU MOHAMMED", "7-Aug-98", "M", "KOGI", "SSCE", "GUDU", "TOLL COLLECTOR", "1-Aug-24", "", ""],
  ["TC", "3", "MESHACK USMAN DANBABA", "25-Dec-88", "M", "NIGER", "SSCE", "GUDU", "TOLL COLLECTOR", "8-Jan-20", "", ""],
  ["TC", "4", "MUHAMMED YUNUSA", "5-May-89", "M", "KOGI", "NCE", "GUDU", "TOLL COLLECTOR", "31-May-17", "", ""],
  ["TC", "5", "ADAMU IBRAHIM", "22-Feb-90", "M", "KOGI", "", "GUDU", "TOLL COLLECTOR", "8-Jan-20", "", ""],
  ["TC", "6", "HAMZA MOMOH", "12-Nov-93", "M", "KOGI", "ND-QS & BLDG TECH.; HND- BLDG TECH.", "WUSE", "TOLL COLLECTOR", "15-Mar-14", "1-Jan-26", ""],
  ["TC", "7", "MAIKASUWA JOHN MADALLA", "28-Sep-98", "M", "FCT", "", "WUSE", "FRONT DESK", "2-Jun-17", "", ""],
  ["TC", "8", "YAKUBU GARBA MAISAMARI", "1-Oct-83", "M", "GOMBE", "SSCE (DRIVING CERTIFICATION)", "WUSE", "TOLL COLLECTOR", "20-Feb-13", "", ""],
  ["TC", "9", "UMAR ALIYU", "19-Jun-91", "M", "NASARAWA", "", "WUSE", "TOLL COLLECTOR", "28-Nov-17", "", ""],
  ["TC", "10", "ABDULFATAI YAKUBU", "1-Oct-90", "M", "KOGI", "SSCE", "WUSE", "TOLL COLLECTOR", "13-Aug-18", "", ""],
  ["TC", "11", "CLARKSON K. OBADIAH", "24-Dec-80", "M", "TARABA", "SSCE", "WUSE", "TOLL COLLECTOR", "11-Oct-16", "1-Jan-26", ""],
  ["TC", "12", "DANIEL O. OKECHUKWU", "27-Mar-03", "M", "IMO", "BSC. ACCOUNTING (in view)", "WUSE", "TOLL COLLECTOR", "9-Apr-21", "", ""],
  ["TC", "13", "GARBA IBRAHIM", "10-May-80", "M", "BAUCHI", "", "WUSE", "TOLL COLLECTOR", "Jun-13", "", ""],
  ["TC", "14", "IREBISI UCHECHI GLORIA", "22-May-88", "F", "IMO", "BSc. ACCOUNTING", "WUSE", "TOLL COLLECTOR", "15-Apr-21", "", ""],
  ["TC", "15", "MATHEW BALA TARI", "16-Feb-89", "M", "BAUCHI", "ND-CRIME MGT & CONTROL", "WUSE", "TOLL COLLECTOR", "9-Jan-20", "", ""],
  ["TC", "16", "NGOZI ADUMIKE MIKE", "15-Aug-81", "F", "ENUGU", "SSCE", "WUSE", "TOLL COLLECTOR", "29-Mar-18", "", ""],
  ["TC", "17", "OKORO JAMES NNANYERE", "4-Jun-83", "M", "EBONYI", "B.Ed - ADMIN & PLANNING", "WUSE", "TOLL COLLECTOR", "8-Apr-21", "", ""],
  ["TC", "18", "SALIU MOMOH JIMOH", "10-Oct-86", "M", "KOGI", "BSc. POLITICAL SCIENCE (in view)", "WUSE", "TOLL COLLECTOR", "9-Apr-21", "", ""],
  ["TC", "19", "SALISU BALARABE DOMA", "4-Jan-91", "M", "BAUCHI", "SSCE", "WUSE", "TOLL COLLECTOR", "2-Mar-21", "", ""],
  ["TC", "20", "TIJJANI AJIBILI", "14-Mar-84", "M", "KOGI", "", "WUSE", "TOLL COLLECTOR", "16-Jul-10", "", ""],
  ["TC", "21", "USMAN ABUBAKAR", "11-Apr-96", "M", "KOGI", "HND-PUBLIC ADMINISTRATION", "WUSE", "TOLL COLLECTOR", "3-Dec-19", "", ""],
  ["TC", "22", "YAKUBU HASSANA HASSAN", "23-Apr-88", "F", "KOGI", "SSCE", "WUSE", "TOLL COLLECTOR", "4-Jan-23", "", ""],
  ["TC", "23", "YAKUBU NUHU MUSA", "11-Nov-91", "M", "KADUNA", "", "WUSE", "TOLL COLLECTOR", "31-Jan-22", "", ""],
  ["TC", "24", "JIBRIN MOHAMMED MACO", "27-Jul-93", "M", "KOGI", "HND-PUBLIC ADMINISTRATION", "WUSE", "TOLL COLLECTOR", "13-Jan-20", "", ""],
  ["TC", "25", "EKECHUKWU UJUNWA", "26-Sep-90", "F", "IMO", "BSc. PUBLIC ADMIN", "WUSE", "OFFICE ASSISTANT", "11-Mar-21", "", ""],
  ["TC", "26", "TSAV SAMUEL NYITAMEN", "3-Feb-86", "M", "TARABA", "HND - PURCHASING & SUPPLY", "MAITAMA FM", "ACCOUNTS UNIT", "16-Nov-21", "", ""],
  ["TC", "27", "SALAUDEEN AISHA", "27-Feb-93", "M", "KOGI", "SSCE", "MAITAMA FM", "TOLL COLLECTOR", "20-Apr-21", "1-Jan-26", ""],
  ["TC", "28", "HARRISON MATHIAS ISHAKU", "24-Sep-88", "M", "TARABA", "SSCE", "ZONE 3", "TOLL COLLECTOR", "17-Sep-21", "", ""],
  ["TC", "29", "GARBA BUHARI", "20-Mar-86", "M", "NIGER", "SSCE", "ZONE 3", "TOLL COLLECTOR", "1-Mar-17", "1-Jan-26", ""],
  ["TC", "30", "USMAN BINYA. IBRAHIM", "23-Dec-88", "M", "KANO", "", "ZONE 3", "TOLL COLLECTOR", "10-Aug-12", "1-Jan-26", ""],
  ["TC", "31", "NAFIU MUSTAPHA", "10-Jun-99", "M", "KATSINA", "", "ZONE 3", "TOLL COLLECTOR", "20-Feb-23", "", ""],
  ["TC", "32", "ADEBAYO IBUKUNOLUWA", "27-Jul-93", "M", "OSUN", "", "ZONE 3", "TOLL COLLECTOR", "29-Sep-21", "1-Jan-26", ""],
  ["TC", "33", "EBUGA ARIGU VICTOR", "18-May-00", "M", "NASARAWA", "NCE", "ZONE 3", "TOLL COLLECTOR", "24-Feb-22", "", ""],
  ["TC", "34", "ICHIRE NKECHINYERE NSOR", "1-Jan-90", "F", "CROSS RIVER", "NCE", "ZONE 3", "TOLL COLLECTOR", "20-Mar-24", "", ""],
  ["TC", "35", "NIKE OJO", "10-May-90", "F", "OSUN", "OND-HOSPITALITY MGT", "ZONE 3", "TOLL COLLECTOR", "8-Aug-17", "", ""],
  ["TC", "36", "IYAJI UMAR ALHASSAN", "23-Jun-85", "M", "KOGI", "OND-PUBLIC ADMIN", "KADO", "TOLL COLLECTOR", "16-Sep-09", "", ""],
  ["TC", "37", "ABUBAKAR SULEIMAN", "2-May-88", "M", "KANO", "", "KADO", "TOLL COLLECTOR", "11-Nov-13", "", ""],
  ["TC", "38", "SANI IBRAHIM", "12-Jun-96", "M", "BAUCHI", "SSCE", "KADO", "TOLL COLLECTOR", "8-Feb-22", "", ""],
  ["TC", "39", "SANUSI HARUNA", "1-Jan-96", "M", "KATSINA", "NCE", "KADO", "TOLL COLLECTOR", "21-Feb-23", "", ""],
  ["TC", "40", "ANYIA DENNIS", "21-Dec-64", "M", "BENUE", "", "KADO", "TOLL COLLECTOR", "1-Jun-12", "", ""],
  ["TC", "41", "MOHAMMED ABDULLAHI", "10-Sep-92", "M", "KADUNA", "OND-PUBLIC ADMIN", "KADO", "TOLL COLLECTOR", "8-Jan-20", "", ""],
  ["TC", "42", "IBRAHIM RIDWAN", "10-May-85", "M", "KADUNA", "", "KADO", "TOLL COLLECTOR", "30-Nov-21", "", ""],
  ["TC", "43", "OKETAYO B. JANET", "14-Sep-01", "F", "OYO", "SSCE", "AREA 1&2", "TOLL COLLECTOR", "13-Feb-24", "", ""],
  ["TC", "44", "UBA MUSA MAGAJI", "6-Oct-88", "M", "PLATEAU", "", "AREA 1&2", "TOLL COLLECTOR", "13-Mar-13", "", ""],
  ["TC", "45", "KELVIN GLORIA", "17-Aug-94", "F", "GOMBE", "BSc. SOCIOLOGY", "AREA 1 & 2", "TOLL COLLECTOR", "11-Jan-17", "1-Jan-26", ""],
  ["TC", "46", "GRACE JOHN", "24-Jun-84", "F", "NASARAWA", "", "AREA 1&2", "TOLL COLLECTOR", "11-Oct-16", "", ""],
  ["TC", "47", "YUSUF MUHAMMAD", "13-Feb-00", "M", "NIGER", "ND-SCIENCE LAB. TECH.", "AREA 1&2", "TOLL COLLECTOR", "27-May-24", "", ""],
  ["TC", "48", "LUKA AHMADU", "2-Jan-93", "M", "KADUNA", "SSCE", "AREA 1 & 2", "TOLL COLLECTOR", "18-Mar-24", "1-Jan-26", ""],
  ["TC", "49", "ABDULLAHI HAMMA", "", "M", "BORNO", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "20-Mar-20", "", ""],
  ["TC", "50", "ABUBAKAR DAHIRU", "", "M", "", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "", "", ""],
  ["TC", "51", "ADAMU YAKUBU", "10-Mar-80", "M", "BAUCHI", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "24-May-18", "", ""],
  ["TC", "52", "GALI LAWAN DANTSOHO", "23-Feb-82", "M", "KANO", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "25-May-18", "", ""],
  ["TC", "53", "HUSSAINI MAIKUDI", "5-Feb-88", "M", "KATSINA", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "29-May-18", "", ""],
  ["TC", "54", "IDRIS YUSHA'U", "16-Dec-91", "M", "NIGER", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "7-Dec-20", "", ""],
  ["TC", "55", "IYOL GODWIN", "15-May-74", "M", "BENUE", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "10-Dec-20", "", ""],
  ["TC", "56", "MAGDALINE BAKO", "22-Apr-86", "F", "KADUNA", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "15-Oct-11", "", ""],
  ["TC", "57", "MEMUNAT UMAR", "27-May-81", "F", "KOGI", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "18-Jan-24", "", ""],
  ["TC", "58", "MU'AZU ABDULLAHI", "1-Feb-84", "M", "KOGI", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "3-Apr-16", "", ""],
  ["TC", "59", "MUDASHIRU BELLO", "1-Jan-89", "M", "SOKOTO", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "24-May-18", "", ""],
  ["TC", "60", "PETER ABANNATI", "2-Feb-77", "M", "KADUNA", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "19-Nov-09", "", ""],
  ["TC", "61", "STELLA CHISOM EKECHUKWU", "10-Oct-80", "F", "IMO", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "27-Feb-16", "", ""],
  ["TC", "62", "WASINI JANGARI", "14-Feb-00", "F", "ADAMAWA", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "5-Dec-23", "", ""],
  ["TC", "63", "YAKUBU IBRAHIM MOHAMMED", "1-Jan-86", "M", "KANO", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "23-May-18", "", ""],
  ["TC", "64", "YUNUSA AROME", "12-Jan-90", "M", "KOGI", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "13-Feb-20", "", ""],
  ["TC", "65", "HABILA BARTHOLOMEW", "29-Sep-90", "M", "KADUNA", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "27-May-24", "", ""],
  ["TC", "66", "ZAINAB O. YUSUF", "27-Dec-88", "F", "KOGI", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "13-Nov-23", "", ""],
  ["TC", "67", "ISAH ABDULLAHI", "16-Oct-92", "M", "GOMBE", "", "Dei-Dei Mkt T", "TOLL COLLECTOR", "4-Oct-19", "", ""],
  ["TC", "68", "MOHAMMED SAMUEL", "6-Oct-85", "M", "KOGI", "SSCE", "Dei-Dei Mkt T", "TOLL COLLECTOR", "30-Jan-24", "", ""],
  ["TC", "69", "ABDULAZEEZ AYUBA", "2-Sep-85", "M", "KOGI", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "8-May-14", "", ""],
  ["TC", "70", "ADAMU MUSA", "20-Sep-93", "M", "BORNO", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "18-Nov-13", "", ""],
  ["TC", "71", "SHAIBU YUSUF", "6-Feb-88", "M", "KADUNA", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "27-Jun-13", "", ""],
  ["TC", "72", "ENDURANCE SUNDAY", "", "", "", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "", "", ""],
  ["TC", "73", "JEREMIAH HARUNA BULLE", "", "", "", "", "Dei-Dei Mkt", "TOLL COLLECTOR", "", "", ""],
  ["TC", "74", "ABDULSALAM HOMAMMED", "15-Jan-85", "M", "ADAMAWA", "", "GARKI MM", "TOLL COLLECTOR", "16-Mar-13", "", ""],
  ["TC", "75", "ATTAH SUNDAY", "28-Dec-88", "M", "BENUE", "ND - LAW", "GARKI MM", "TOLL COLLECTOR", "3-Sep-18", "", ""],
  ["TC", "76", "GALADIMA YAKUBU MATHEW", "12-Dec-82", "M", "KADUNA", "BSc. ENTP. & BUS. MGT.(in view)", "GARKI MM", "TOLL COLLECTOR", "2-Mar-21", "", ""],
  ["TC", "77", "CHIDOKA DAVID EBUKA", "19-Oct-97", "M", "ANAMBRA", "SSCE", "GARKI MM", "TOLL COLLECTOR", "1-Apr-25", "", ""],
  ["TC", "78", "MAGDALINE NIMFAS", "31-Jul-89", "F", "ADAMAWA", "", "GARKI MM", "TOLL COLLECTOR", "12-Feb-24", "", ""],
  ["TC", "79", "NAFIU ALIYU", "8-Sep-03", "M", "KATSINA", "ND - LIB. & INFO. SCI. (in view)", "GARKI MM", "TOLL COLLECTOR", "21-Feb-23", "", ""],
  ["TC", "80", "OLUWAKEMI OMOSHOLA DAVID", "28-Dec-86", "F", "KOGI", "ND - FOOD SCIENCE & TECH.", "GARKI MM", "TOLL COLLECTOR", "26-Oct-11", "", ""],
  ["TC", "81", "UGBOGA HAPPINESS OMALE", "1-Sep-83", "F", "BENUE", "", "GARKI MM", "TOLL COLLECTOR", "11-Nov-13", "", ""],
  ["TC", "82", "VICTOR EKONG", "1976", "M", "AKWAIBOM", "", "GARKI MM", "TOLL COLLECTOR", "1-Jun-12", "", ""],
  ["TC", "83", "ALABURA MAGDALINE", "27-Aug-95", "F", "TARABA", "", "GARKI MM", "TOLL COLLECTOR", "19-Jul-18", "", ""],
  ["TC", "84", "HARUNA MOHAMMED", "20-Feb-87", "M", "NIGER", "SSCE", "GARKI MM", "TOLL COLLECTOR", "23-Jan-19", "", ""],
  ["TC", "85", "EMMANUEL IMONINA", "14-Jan-85", "M", "DELTA", "SSCE", "GARKI MM", "TOLL COLLECTOR", "3-Nov-25", "", ""],
  ["TC", "86", "BARIRA MUHAMMED", "21-Mar-88", "F", "KOGI", "BSC. POLITICAL SCIENCE", "NEW AREA 10", "TOLL COLLECTOR", "2-Jun-25", "", ""],
  ["TC", "87", "WISDOM DAN", "8-Oct-98", "F", "KOGI", "ND - SURVEYING & GEO-INFORMATICS", "NEW AREA 10", "TOLL COLLECTOR", "2-Jun-25", "", ""],
  ["TC", "88", "YEMI DANIEL", "11-May-85", "F", "NASARAWA", "", "NEW AREA 10", "TOLL COLLECTOR", "21-Nov-12", "", ""],
  ["TC", "89", "OKONKWO ANSILIN UCHE", "5-Sep-79", "M", "ANAMBRA", "BA. CRS; DIPLOMA-JOURNALISM", "NEW AREA 10", "TOLL SUPERVISOR", "1-Apr-25", "", ""],
  ["TC", "90", "AISHAT MOHAMMED", "5-May-97", "F", "KOGI", "SSCE", "NEW AREA 10", "TOLL COLLECTOR", "3-Jan-24", "", ""],
  ["TC", "91", "CYRUS BITRUS", "3-Mar-87", "M", "KADUNA", "", "KAURA", "TOLL SUPERVISOR", "1-Apr-08", "1-Jan-26", ""],
  ["TC", "92", "MUSA I. TIMOTHY", "2-Apr-73", "M", "KADUNA", "ND - PUBLIC ACCOUNTING & AUDITING", "KAURA", "TOLL COLLECTOR", "1-Jul-09", "1-Jan-26", ""],
  ["TC", "93", "IBRAHIM JIKKA", "1-Jan-75", "M", "ADAMAWA", "", "KAURA", "TOLL COLLECTOR", "5-Oct-16", "1-Jan-26", ""],
  ["TC", "94", "HARUNA SALIHU", "21-Jan-95", "M", "NIGER", "ND - ELECT./ELECT. ENG.", "KAURA", "TOLL COLLECTOR", "30-May-24", "", ""],

  // ================= TASKFORCE =================
  ["TF", "1", "ABDULLAHI ABUBAKAR", "18-Aug-86", "M", "PLATEAU", "", "GUDU", "TASKFORCE", "14-Nov-13", "1-Jan-26", ""],
  ["TF", "2", "AKPU AMOS BULUS", "10-May-82", "M", "NASARAWA", "", "GUDU", "TASKFORCE", "18-Feb-13", "", ""],
  ["TF", "3", "BONIFACE EBEKU", "3-Apr-82", "M", "CROSS RIVER", "", "GUDU", "TASKFORCE", "14-Feb-06", "", ""],
  ["TF", "4", "DAWUDA BALA KAWAI", "6-Sep-68", "M", "KADUNA", "ND-ACCOUNTING", "GUDU", "TASKFORCE", "2-Jun-17", "", ""],
  ["TF", "5", "MANDELA MATHEW", "18-Jan-91", "M", "KADUNA", "", "GUDU", "TASKFORCE", "1-Mar-18", "", ""],
  ["TF", "6", "PHILIP HASSAN YIKAM", "1-Aug-87", "M", "PLATEAU", "", "GUDU", "TASKFORCE", "16-Oct-14", "", ""],
  ["TF", "7", "SULEIMAN  MOHAMMED", "26-Oct-87", "M", "KADUNA", "", "GUDU", "TASKFORCE", "5-Oct-16", "", ""],
  ["TF", "8", "CHINDO TIYA", "15-May-87", "M", "NASARAWA", "", "GUDU", "TASKFORCE", "13-Jan-10", "", ""],
  ["TF", "9", "CHANZER ISAAC DONATUS", "27-Feb-73", "M", "BENUE", "", "GUDU", "TASKFORCE", "7-Jul-11", "", ""],
  ["TF", "10", "FRIDAY IME", "1-Feb-80", "M", "AKWAIBOM", "", "GUDU", "TASKFORCE", "14-Feb-06", "", ""],
  ["TF", "11", "BASIRU AHMADU", "2-Feb-82", "M", "FCT", "BSC. SOCIOLOGY", "WUSE", "TASKFORCE", "12-Apr-14", "", ""],
  ["TF", "12", "ALEX  CHISOM OGBUNEKE", "11-Oct-96", "M", "ENUGU", "BSc. ECONOMICS", "WUSE", "ACCOUNTS", "9-Mar-18", "1-Jan-26", ""],
  ["TF", "13", "BASHAR HARUNA", "5-Aug-86", "M", "ZAMFARA", "", "WUSE", "TASK/W/BARROW", "1-Sep-23", "", ""],
  ["TF", "14", "BASHIR IBRAHIM", "12-Sep-88", "M", "NIGER", "", "WUSE", "TASKFORCE", "15-Jan-14", "", ""],
  ["TF", "15", "BENJAMIN BWAI EMMANUEL", "Nov-87", "M", "PLATEAU", "SSCE", "WUSE", "TASKFORCE", "2-Jun-23", "", ""],
  ["TF", "16", "RILWAN LAWAL", "10-Nov-97", "M", "KADUNA", "ND-COOP. ECONS. & MGT; HND (in view)", "WUSE", "TASKFORCE", "10-Aug-18", "", ""],
  ["TF", "17", "DAHIRU MOHAMMED BUHARI", "16-May-87", "M", "NIGER", "NCE", "WUSE", "TASKFORCE", "1-Sep-20", "", ""],
  ["TF", "18", "DANJUMA SA'ADU", "30-Dec-82", "M", "NIGER", "", "WUSE", "TASKFORCE", "23-Nov-20", "", ""],
  ["TF", "19", "UMAR IDRIS", "21-Jul-90", "M", "KANO", "", "WUSE", "TASKFORCE", "1-Jul-15", "", ""],
  ["TF", "20", "USMAN ABDULKERIM", "14-Feb-85", "M", "KOGI", "NCE", "WUSE", "TASKFORCE", "25-Feb-21", "", ""],
  ["TF", "21", "MONDAY SAMUEL", "3-Apr-73", "M", "KOGI", "SSCE (TECHNICIAN)", "WUSE", "TASKFORCE", "4-Oct-24", "", ""],
  ["TF", "22", "ABDULLAHI UMAR", "1-Jan-00", "M", "ZAMFARA", "", "WUSE", "TASKFORCE", "4-Oct-24", "", ""],
  ["TF", "23", "ABDULLAHI ISA", "22-Dec-88", "M", "ZAMFARA", "", "WUSE", "TASKFORCE", "4-Oct-24", "", ""],
  ["TF", "24", "YAKUBU IBRAHIM", "1-Jan-86", "M", "KEBBI", "", "WUSE", "TASKFORCE", "7-Oct-24", "", ""],
  ["TF", "25", "AMOS YUSUF", "29-Nov-98", "M", "NASARAWA", "SSCE", "WUSE", "TASKFORCE", "4-Oct-24", "", ""],
  ["TF", "26", "ZUBAIRU HARUNA", "25-Sep-94", "M", "BORNO", "", "WUSE", "TASKFORCE", "14-Oct-24", "", ""],
  ["TF", "27", "BARIKI GODIYA", "10-Jan-78", "M", "BAUCHI", "ND-AGRIC. TECHNOLOGY", "WUSE", "TASKFORCE", "1-Nov-17", "", ""],
  ["TF", "28", "NURA MOHAMMED", "1-Jan-83", "M", "ZAMFARA", "SSCE", "WUSE", "TASKFORCE", "23-Jan-20", "", ""],
  ["TF", "29", "SULE BAKO ISA", "13-Jul-87", "M", "KADUNA", "", "WUSE", "TASKFORCE", "15-Dec-21", "", ""],
  ["TF", "30", "MONDAY AMALI", "19-Oct-86", "M", "BENUE", "", "WUSE", "TASKFORCE", "4-Apr-13", "", ""],
  ["TF", "31", "ISAH DANLADI BASHIRU", "4-Jan-00", "M", "FCT", "", "WUSE", "TASKFORCE", "1-Feb-24", "", ""],
  ["TF", "32", "SUNDAY MAMMA", "2-Feb-94", "M", "NASARAWA", "", "WUSE", "TASKFORCE", "11-Sep-23", "", ""],
  ["TF", "33", "AMODU SUNDAY MASHACK", "15-Jul-85", "M", "BENUE", "SSCE", "WUSE", "TASKFORCE", "18-Mar-21", "", ""],
  ["TF", "34", "BITRUS ALIYU ATTAH", "13-Jan-85", "M", "NASARAWA", "SSCE", "WUSE", "TASKFORCE", "12-Feb-20", "", ""],
  ["TF", "35", "ANI LEONARD", "8-Aug-67", "M", "ENUGU", "", "WUSE", "TASKFORCE", "1-Jul-11", "", ""],
  ["TF", "36", "INDYER ISAAC", "6-Nov-84", "M", "BENUE", "SSCE", "WUSE", "TASKFORCE", "3-Feb-20", "", ""],
  ["TF", "37", "CHRISTOPHER ENEFOLA", "", "M", "", "", "WUSE", "TASKFORCE", "", "", ""],
  ["TF", "38", "UJULLU LEO JOSEPH", "2-Nov-94", "M", "ADAMAWA", "SSCE", "WUSE", "TASKFORCE", "21-Feb-22", "", ""],
  ["TF", "39", "SILAS ISAAC", "11-May-82", "M", "NASARAWA", "", "WUSE", "TASKFORCE", "10-Jun-10", "", ""],
  ["TF", "40", "NASIRU ABUBAKAR", "", "M", "", "", "WUSE", "TASKFORCE", "", "", ""],
  ["TF", "41", "MOHAMMED AUWAL", "", "M", "", "", "WUSE", "TASKFORCE", "", "", ""],
  ["TF", "42", "ADAMU IBRAHIM", "", "M", "", "", "WUSE", "TASKFORCE", "", "", ""],
  ["TF", "43", "ABDULLAHI ALIYU", "", "M", "", "", "WUSE", "TASKFORCE", "", "", ""],
  ["TF", "44", "DAUDA YAKUBU ADAMU", "5-Aug-85", "M", "KADUNA", "", "ZONE 3", "TASKFORCE", "7-Aug-09", "", ""],
  ["TF", "45", "KABIRU IBRAHIM", "2-Feb-83", "M", "KADUNA", "", "ZONE 3", "TASKFORCE", "9-May-08", "", ""],
  ["TF", "46", "MONDAY GOTING", "19-Oct-85", "M", "PLATEAU", "", "ZONE 3", "TASKFORCE", "15-Jun-21", "", ""],
  ["TF", "47", "MUNTARI UMAR", "10-Feb-98", "M", "KATSINA", "", "ZONE 3", "TASKFORCE", "09/09/2009, 14/10/2024", "", ""],
  ["TF", "48", "ABDULLAHI MADU", "22-Apr-82", "M", "BORNO", "", "ZONE 3", "TASKFORCE", "1-Feb-08", "", ""],
  ["TF", "49", "JOHN AUDU", "5-Oct-79", "M", "KOGI", "", "ZONE 3", "TASKFORCE", "", "", ""],
  ["TF", "50", "AUDU HUSSEIN", "13-Jul-86", "M", "KOGI", "SSCE", "ZONE 3", "TASKFORCE", "24-Jan-22", "1-Jan-26", ""],
  ["TF", "51", "ALIYU ABUBAKAR", "15-May-82", "M", "BENUE", "OND-PUBLIC ADMIN", "KADO", "TASKFORCE", "10-Nov-14", "", ""],
  ["TF", "52", "HANNAFI SALIHU", "19-Mar-88", "M", "KEBBI", "", "KADO", "TASKFORCE", "1-Mar-09", "", ""],
  ["TF", "53", "PATRICK IKYO", "15-May-79", "M", "BENUE", "HND-ESTATE MGT", "KADO", "TASKFORCE", "1-Mar-09", "1-Jan-26", ""],
  ["TF", "54", "RABIU BELLO", "14-Oct-88", "M", "KOGI", "SSCE", "KADO", "TASKFORCE", "1-Jul-13", "", ""],
  ["TF", "55", "ZAKARI SHUAIBU", "15-Feb-88", "M", "GOMBE", "", "KADO", "TASKFORCE", "12-Feb-12", "", ""],
  ["TF", "56", "MOHAMMED ABDULLAHI", "17-May-89", "M", "KADUNA", "ND-PUBLIC ADMIN.", "KADO", "TASKFORCE", "12-Jun-17", "", ""],
  ["TF", "57", "IBRAHIM A. MUSA", "1-May-82", "M", "KANO", "", "KADO", "TASKFORCE", "15-Apr-10", "", ""],
  ["TF", "58", "MOHAMMED LAWAL AHMED", "7-Jul-79", "M", "KOGI", "", "AREA 3", "TASKFORCE", "10-Mar-14", "", ""],
  ["TF", "59", "BAMOR GABRIEL MSUGHTER", "16-Jan-96", "M", "BENUE", "HND-COMPUTER ENG.TECH.", "AREA 1&2", "FACILITY", "13-Feb-24", "", ""],
  ["TF", "60", "OJO OVA", "26-Jan-76", "M", "KOGI", "", "AREA 1&2", "TASKFORCE", "16-Aug-10", "1-Jan-26", ""],
  ["TF", "61", "UBA MICHAEL", "7-May-83", "M", "BAUCHI", "", "AREA 1&2", "TASKFORCE", "1-Nov-08", "", ""],
  ["TF", "62", "HAMZA LIMAN", "", "M", "", "", "AREA 1&2", "TASKFORCE", "", "", ""],
  ["TF", "63", "ADAMU BAZZA", "2-Aug-82", "M", "ADAMAWA", "", "AREA 1&2", "TASKFORCE", "7-Aug-08", "", ""],
  ["TF", "64", "MUHAMMED MUSA", "1-Jul-82", "M", "GOMBE", "", "AREA 1&2", "TASKFORCE", "7-Jun-21", "", ""],
  ["TF", "65", "KEFAS EZEKIEL", "4-Oct-89", "M", "GOMBE", "NCE", "AREA 1&2", "TASKFORCE", "24-Feb-21", "1-Jan-26", ""],
  ["TF", "66", "BAKO SOLOMON", "23-Mar-86", "M", "NASARAWA", "HND-MECHANICAL ENG.", "AREA 1&2", "TASKFORCE", "19-Jan-17", "1-Jan-26", ""],
  ["TF", "67", "SAMAILA IBRAHIM", "2-Mar-86", "M", "BORNO", "NCE", "AREA 1&2", "TASKFORCE", "6-Feb-18", "", ""],
  ["TF", "68", "OKOBIA IBRAHIM ISAH", "11-Mar-94", "M", "TARABA", "ND - AGRIC. TECH.", "AREA 1&2", "TASKFORCE", "7-Feb-18", "1-Jan-26", ""],
  ["TF", "69", "ALIYU SAFWAN", "19-Mar-91", "M", "ADAMAWA", "", "AREA 1&2", "TASKFORCE", "8-Jun-21", "", ""],
  ["TF", "70", "EDEH CHIBUZOR", "13-Apr-73", "M", "ENUGU", "", "AREA 1&2 (Night)", "SECURITY", "26-Jul-22", "", ""],
  ["TF", "71", "MUSA JIBRIN", "", "M", "", "", "AREA 1&2", "TASKFORCE", "", "", ""],
  ["TF", "72", "LENGE DEREK OBED", "18-Mar-96", "M", "PLATEAU", "BSC-SOCIOLOGY", "Dei-Dei Mkt", "ACCOUNTS", "6-Oct-16", "", ""],
  ["TF", "73", "YAHAYA ABDULRAHMAN", "1-Jan-92", "M", "NIGER", "", "Dei-Dei Mkt", "TASKFORCE", "2-Feb-09", "", ""],
  ["TF", "74", "MUAZU HASSAN AUDU", "1-Feb-75", "M", "BORNO", "", "Dei-Dei Mkt", "TASKFORCE", "4-Oct-19", "", ""],
  ["TF", "75", "BILA SANI", "5-May-86", "M", "FCT", "", "Dei-Dei Mkt", "TASKFORCE", "24-Jan-19", "", ""],
  ["TF", "76", "JIBRIN AMINU", "20-May-88", "M", "NIGER", "", "Dei-Dei Mkt", "TASKFORCE", "30-Sep-15", "", ""],
  ["TF", "77", "UMAR ABUBAKAR BANKI", "11-Nov-74", "M", "BORNO", "", "Dei-Dei Mkt", "TASKFORCE", "22-Feb-23", "", ""],
  ["TF", "78", "SULE GIFT BLESSING", "9-Dec-94", "F", "KOGI", "", "Dei-Dei Mkt", "TASKFORCE", "31-Jan-18", "", ""],
  ["TF", "79", "ABUBAKAR HASSAN SALEH", "5-Jan-83", "M", "KANO", "", "Dei-Dei Mkt", "TASKFORCE", "15-Apr-10", "", ""],
  ["TF", "80", "ABDULAZEEZ OMEIZA AYUBA", "20-Jan-82", "M", "KOGI", "", "Dei-Dei Mkt", "TASKFORCE", "18-Dec-09", "", ""],
  ["TF", "81", "MAYAKI MAHMUD", "15-May-80", "M", "KOGI", "", "Dei-Dei Mkt", "TASKFORCE", "29-Apr-13", "", ""],
  ["TF", "82", "SALIHU ABEDO", "1-Jan-87", "M", "KOGI", "", "Dei-Dei Mkt", "TASKFORCE", "1-Oct-11", "", ""],
  ["TF", "83", "AHMED MAISARKI ABDULLAHI", "2-Feb-94", "M", "KANO", "BSC-BUSINESS ADMIN", "Dei-Dei Mkt", "TASKFORCE", "1-Jul-25", "", ""],
  ["TF", "84", "IDRIS SULE", "26-Jun-78", "M", "EDO", "OND", "Dei-Dei Mkt", "TASKFORCE", "28-Nov-12", "", ""],
  ["TF", "85", "ABUBAKAR JIBRIN", "", "M", "", "", "Dei-Dei Mkt", "TASKFORCE", "", "", ""],
  ["TF", "86", "EGBE ISAAC OLA", "26-Dec-83", "M", "BENUE", "", "GIM", "TASKFORCE", "1-Oct-11", "", ""],
  ["TF", "87", "MANSIR ABDULLAHI", "6-Mar-92", "M", "NASARAWA", "", "GIM", "TASKFORCE", "23-Jan-20", "1-Jan-26", ""],
  ["TF", "88", "SHAFIU YUSUF", "3-Oct-93", "M", "KATSINA", "BSC-", "GIM", "TASKFORCE", "21-Oct-09", "", ""],
  ["TF", "89", "THEOPHILUS E. OKEY", "10-May-83", "M", "CROSS RIVER", "", "GIM", "TASKFORCE", "15-Mar-13", "", ""],
  ["TF", "90", "PAUL YOHANNA", "15-Nov-82", "M", "BAUCHI", "", "GIM", "TASKFORCE", "1-Nov-08", "1-Jan-26", ""],
  ["TF", "91", "SHAYO OLAGUNDOYE", "6-Jan-88", "M", "ONDO", "", "GIM", "TASKFORCE", "6-Dec-10", "1-Jan-26", ""],
  ["TF", "92", "DAUDA EMMANUEL", "3-Mar-97", "M", "BAUCHI", "SSCE", "GIM", "TASKFORCE", "12-Feb-20", "", ""],
  ["TF", "93", "BENJAMIN HABILA", "30-Jun-87", "M", "PLATEAU", "", "GIM", "TASKFORCE", "10-Oct-19", "", ""],
  ["TF", "94", "ZURKALLAINI AUDU WAZIRI", "2-Feb-93", "M", "YOBE", "", "MAITAMA FM", "TASKFORCE", "4-Mar-24", "1-Jan-26", ""],
  ["TF", "95", "LUCKY DANBABA MAIKARFI", "2-Feb-79", "M", "KADUNA", "", "GARKI MM", "TASKFORCE", "13-Mar-09", "", ""],
  ["TF", "96", "KABIRU SULE", "26-Jul-86", "M", "BAUCHI", "", "GARKI MM", "TASKFORCE", "15-Aug-15", "", ""],
  ["TF", "97", "ADAMU MUSA", "14-Feb-78", "M", "KOGI", "", "GARKI MM", "TASKFORCE", "14-Mar-11", "", ""],
  ["TF", "98", "ZUBAIRU DAHIRU", "10-Mar-96", "M", "NIGER", "", "GARKI MM", "TASKFORCE", "1-Mar-21", "", ""],
  ["TF", "99", "ABUBAKAR ISA BAKO", "8-Apr-91", "M", "KANO", "", "GARKI MM", "TASKFORCE", "2-Mar-20", "", ""],
  ["TF", "100", "YUSUF LAWAL", "15-May-83", "M", "KOGI", "OND", "GARKI MM", "TASKFORCE", "17-Feb-14", "", ""],
  ["TF", "101", "ISAH AUWAL", "3-Jun-95", "M", "NASARAWA", "NCE", "GARKI MM", "TASKFORCE", "22-Mar-21", "", ""],
  ["TF", "102", "NWONU OBINNA", "", "M", "", "", "GARKI MM", "TASKFORCE", "", "", ""],
  ["TF", "103", "BUKAR MADU", "15-Jan-83", "M", "BORNO", "", "GARKI MM", "TASKFORCE", "1-Mar-21", "", ""],
  ["TF", "104", "CHRISTOPHER OKANGLA", "13-May-83", "M", "BENUE", "", "GARKI MM", "TASKFORCE", "9-Mar-13", "", ""],
  ["TF", "105", "ABDULLAHI O. MUHAMMED", "5-Feb-87", "M", "KOGI", "", "GARKI MM", "TASKFORCE", "14-Feb-13", "", ""],
  ["TF", "106", "GODWIN ADANO", "11-Oct-82", "M", "KOGI", "", "GARKI MM", "TASKFORCE", "5-Jun-12", "", ""],
  ["TF", "107", "SHEIDU SULEIMAN", "20-Aug-80", "M", "KOGI", "", "GARKI MM", "TASKFORCE", "16-Nov-14", "", ""],
  ["TF", "108", "USMAN ADAMU", "6-Jul-80", "M", "ADAMAWA", "", "GARKI MM", "TASKFORCE", "26-Mar-14", "", ""],
  ["TF", "109", "OLUTAYO SAMUEL", "", "M", "", "", "GARKI MM", "TASKFORCE", "", "", ""],
  ["TF", "110", "ABDULLAHI BABAJI", "10-Jan-89", "M", "BAUCHI", "", "GARKI MM", "TASKFORCE", "9-Oct-24", "", ""],
  ["TF", "111", "WILLIAM ADAJI", "16-Apr-85", "M", "KOGI", "", "GARKI MM", "TASKFORCE", "5-Feb-20", "", ""],
  ["TF", "112", "ABDULWAHAB JATTO  OMEIZA", "26-May-92", "M", "KOGI", "", "GARKI MM", "TASKFORCE", "8-Mar-21", "", ""],
  ["TF", "113", "EGWUAGHA VICTOR OKECHUKWU", "14-Feb-80", "M", "ABIA", "ND-INFO. MGT. TECH.", "GARKI MM", "TASKFORCE", "12-May-23", "", ""],
  ["TF", "114", "BELLO ISHAKU", "4-Mar-84", "M", "GOMBE", "", "GARKI MM", "TASKFORCE", "1-Jul-11", "", ""],
  ["TF", "115", "SAMUEL SHAMMAH", "13-Feb-75", "M", "NASARAWA", "", "GARKI MM", "TASKFORCE", "1-Apr-10", "", ""],
  ["TF", "116", "SA'AD SHEHU", "9-Jul-84", "M", "KADUNA", "NCE", "GARKI MM", "TASKFORCE", "26-May-23", "", ""],
  ["TF", "117", "SAFIANU UBAIDULLAH", "8-Aug-97", "M", "BAUCHI", "BSC. CHEMISTRY", "GARKI MM", "TASKFORCE", "2-Jun-25", "", ""],
  ["TF", "118", "EMMANUEL ADDI", "31-Jan-75", "M", "BENUE", "", "NYANYA", "TASKFORCE", "14-Feb-23", "", ""],
  ["TF", "119", "FRED AGAMA MBONTA", "28-Jul-69", "M", "CROSSRIVERS", "", "NYANYA", "TASKFORCE", "7-Dec-12", "", ""],
  ["TF", "120", "ISA YUSUF GAMBO", "12-Jul-89", "M", "NASARAWA", "NCE", "NYANYA", "TASKFORCE", "14-Jan-22", "", ""],
  ["TF", "121", "JAPHET YAMTAI", "17-Aug-84", "M", "ADAMAWA", "", "NYANYA", "TASKFORCE", "Sep-12", "", ""],
  ["TF", "122", "ASEGIEME MICHEAL", "2-Oct-76", "M", "EDO", "HND-PUBLIC ADMIN", "KAURA", "TASKFORCE", "24-Jan-22", "1-Jan-26", ""],
  ["TF", "123", "JOHN OGBONNA", "23-Dec-85", "M", "EBONYI", "", "KAURA", "TASKFORCE", "26-Sep-12", "1-Jan-26", ""],
  ["TF", "124", "SUNDAY LOMIS", "5-Aug-86", "M", "ADAMAWA", "", "KAURA", "TASKFORCE", "5-Jun-23", "1-Jan-26", ""],
  ["TF", "125", "RABILU UMAR", "3-May-94", "M", "KATSINA", "NCE", "KAURA", "TASKFORCE", "5-Jun-23", "", ""],
  ["TF", "126", "AHMED ABDULRAHAMAN", "15-Mar-84", "M", "KOGI", "SSCE", "KAURA", "TASKFORCE", "3-May-23", "1-Jan-26", ""],
  ["TF", "127", "IBRAHIM BALA", "11-Nov-89", "M", "NIGER", "", "KAURA", "TASKFORCE", "3-Oct-11", "1-Jan-26", ""],
  ["TF", "128", "IBRAHIM YAHUZA", "13-Jan-89", "M", "ZAMFARA", "", "KAURA", "TASKFORCE", "8-Apr-06", "1-Jan-26", ""],
  ["TF", "129", "HASSAN MADU", "6-May-79", "M", "BORNO", "", "KAURA", "TASKFORCE", "24-May-18", "", ""],
  ["TF", "130", "CHINAZA J. DURUJI", "7-Dec-97", "M", "IMO", "OND-BANKING OPERATIONS; HND-PUB. ADMIN.", "KAURA", "TASKFORCE", "22-Aug-24", "", ""],
  ["TF", "131", "HUSSEINI SHEHU", "21-Dec-96", "M", "KADUNA", "", "KAURA", "TASKFORCE", "26-Mar-14", "", ""],
  ["TF", "132", "YAHAYA ABDULAZEEZ YAHAYA", "19-May-92", "M", "JIGAWA", "B.A. BUSINESS ADMINISTRATION", "NEW AREA 10", "TASKFORCE", "2-Jun-25", "", ""],
  ["TF", "133", "MATHEW OCHALA", "1-Jan-95", "M", "KOGI", "ND-CRIMINOLOGY & CRIMINAL JUSTICE ADMINISTRATION", "NEW AREA 10", "TASKFORCE", "22-Sep-23", "1-Jan-26", ""],
  ["TF", "134", "ABDURRAHMAN IBRAHIM", "3-Aug-97", "M", "BAUCHI", "", "NEW AREA 10", "TASKFORCE", "1-Dec-21", "", ""],
  ["TF", "135", "ISAH ADAM", "19-Jan-94", "M", "KANO", "ND- MANAGEMENT", "NEW AREA 10", "TASKFORCE", "2-Jun-25", "", ""],
  ["TF", "136", "MOHAMMED SAIDU DAUDA", "7-Apr-79", "M", "ADAMAWA", "", "APO A, D & E", "TASKFORCE", "1-Feb-08", "1-Jan-26", ""],
  ["TF", "137", "YAHUZA ALI", "20-Aug-87", "M", "PLATEAU", "", "APO A, D & E", "TASKFORCE", "21-Feb-14", "1-Jan-26", ""],

  // ================= WUMATA TASKFORCE =================
  ["WT", "1", "USMAN DALHART", "3-Feb-79", "M", "KANO", "", "WUSE", "TASKFORCE", "10-Oct-24", "", "Wumata Taskforce"],
  ["WT", "2", "OJO ANTHONY", "18-Apr-83", "M", "KWARA", "BSc. ECONOMICS", "WUSE", "TASKFORCE", "10-Oct-24", "", "Wumata Taskforce"],
  ["WT", "3", "AWURU MADUABUCHI", "3-Aug-95", "M", "EBONYI", "", "WUSE", "TASKFORCE", "8-Nov-24", "", "Wumata Taskforce"],
  ["WT", "4", "KELECHI OREKPE", "21-Sep-81", "M", "ANAMBRA", "", "WUSE", "TASKFORCE", "8-Nov-24", "", "Wumata Taskforce"],
  ["WT", "5", "AMADI CHIZOBA ANCELLEM", "30-Jun-78", "M", "ENUGU", "", "WUSE", "TASKFORCE", "31-Oct-24", "", "Wumata Taskforce"],
  ["WT", "6", "MUHAMMAD ABDULHAMID", "1-Jan-77", "M", "ZAMFARA", "", "WUSE", "TASKFORCE", "31-Oct-24", "", "Wumata Taskforce"],
  ["WT", "7", "IDRIS MOBA MOHAMMED", "1-Jan-84", "M", "ZAMFARA", "", "WUSE", "TASKFORCE", "31-Oct-24", "", "Wumata Taskforce"],
  ["WT", "8", "AKUNNE C. CELESTINE", "13-Mar-78", "M", "ANAMBRA", "", "WUSE", "TASKFORCE", "31-Oct-24", "", "Wumata Taskforce"],
  ["WT", "9", "AGAH STANLEY IKECHUKWU", "20-Feb-70", "M", "ENUGU", "", "WUSE", "TASKFORCE", "31-Oct-24", "", "Wumata Taskforce"],
  ["WT", "10", "KAMALIDEEN MOHAMMED MAS'UDU", "31-Jul-99", "M", "NIGER", "", "WUSE", "TASKFORCE", "13-Nov-24", "", "Wumata Taskforce"],
  ["WT", "11", "EMEKA ANI", "21-Dec-84", "M", "ENUGU", "", "WUSE", "TASKFORCE", "13-Nov-24", "", "Wumata Taskforce"],
  ["WT", "12", "ONYE STANLEY", "3-Mar-75", "M", "ENUGU", "", "WUSE", "TASKFORCE", "13-Nov-24", "", "Wumata Taskforce"],

  // ================= INTERNAL SECURITY =================
  ["SEC", "1", "IBRAHIM CHIROMA", "3-Jul-74", "M", "NIGER", "", "GIM", "SECURITY", "1-Dec-21", "1-Jan-26", "Internal Security"],
  ["SEC", "2", "IBRAHIM KOLO ABACHA", "8-Jan-80", "M", "BAUCHI", "", "DEI DEI B/ZONE", "SECURITY", "21-Nov-22", "", "Internal Security"],
  ["SEC", "3", "OMEJE TIMOTHY", "14-Jun-91", "M", "KOGI", "", "DEI DEI B/ZONE", "SECURITY", "16-Nov-22", "", "Internal Security"],

  // ================= ELECTRICIANS/TECHNICIANS =================
  ["TECH", "1", "BELLO ONIMISI HASSAN", "26-Dec-86", "M", "KOGI", "OND", "GIM", "ELECTRICIAN", "26-Dec-86", "1-Jan-26", ""],
  ["TECH", "2", "BENJAMIN OKPOTU", "19-Apr-87", "M", "BENUE", "ND. MARKETING, CERT OF APPRENTICESHIP", "GUDU", "ELECTRICIAN", "31-Aug-16", "", ""],
  ["TECH", "3", "CLEMENT TIMOTHY ELOM", "27-May-78", "M", "EBONYI", "SSCE", "KAURA", "CARPENTER", "20-Aug-24", "", ""],
  ["TECH", "4", "EZUGWU PETER CHINEDU", "10-Nov-85", "M", "ENUGU", "SSCE", "KAURA", "ELECTRICIAN", "31-May-24", "", ""],
  ["TECH", "5", "LUGARD AYAOSI STEPHEN", "31-Mar-76", "M", "EDO", "", "KADO", "ELECTRICIAN", "23-Apr-24", "1-Apr-26", ""],
  ["TECH", "6", "PHILIP PAM JAMES", "28-Feb-83", "M", "PLATEAU", "ND. ELECTRICAL ELECTRONICS", "WUSE", "ELECTRICIAN", "30-Sep-24", "", ""],
  ["TECH", "7", "ELLAH EMMANUEL", "15-Aug-87", "M", "BENUE", "", "GUDU", "BOREHOLE OPERATOR", "2009", "", ""],
  ["TECH", "8", "MOHAMMED IBRAHIM", "1-Jun-86", "M", "BORNO", "", "GIM", "PLUMBER", "Nov-13", "", ""],

  // ================= INTERNAL CLEANERS =================
  ["CL", "1", "ABDULRAHMAN DAHIRU", "10-Oct-70", "M", "KADUNA", "", "WUSE", "CLEANER", "5-Jan-05", "", ""],
  ["CL", "2", "AYUBA MUHAMMED", "1-Jan-81", "M", "NIGER", "", "GIM", "CLEANER", "1-Dec-21", "1-Jan-26", ""],
  ["CL", "3", "FUMILAYO OMONOGUN", "27-May-73", "F", "KOGI", "", "GARKI", "CLEANER", "", "", ""],
  ["CL", "4", "JATAU ASABE", "15-Feb-74", "F", "KADUNA", "", "DEI-DEI", "CLEANER", "1-Nov-06", "", ""],
  ["CL", "5", "OGA DANIEL EDE", "3-Jun-80", "M", "BENUE", "", "APO A, D & E", "CLEANER", "22-Mar-24", "", ""],
  ["CL", "6", "SAMAILA DAKYEN MAIKANO", "15-May-98", "M", "BAUCHI", "", "GIM", "CLEANER", "27-Dec-23", "1-Jan-26", ""],
  ["CL", "7", "SUBERU GRACE", "8-Dec-73", "F", "KOGI", "", "KADO", "CLEANER", "13-Jan-06", "1-Jan-26", ""],
  ["CL", "8", "KUBILI IBRAHIM", "14-Jun-86", "F", "ADAMAWA", "B.Ed - SOC.STUDIES", "DEI-DEI", "CLEANER", "1-Jul-25", "", ""],
  ["CL", "9", "ABDULLAHI SANI", "5-Dec-81", "M", "KADUNA", "", "DEI-DEI", "CLEANER", "1-Jul-25", "", ""],
  ["CL", "10", "TALATU YUSUF", "11-Dec-86", "F", "NASARAWA", "", "DEI-DEI", "CLEANER", "20-Jun-22", "", ""],
  ["CL", "11", "COMFORT M. OSOROH", "8-Dec-92", "F", "BENUE", "", "KUGBO", "CLEANER", "5-Mar-26", "", ""],
  ["CL", "12", "FRANCISCA ONWUKA", "7-Aug-77", "F", "IMO", "", "UTAKO FM", "CLEANER", "16-Mar-26", "", ""],
  ["CL", "13", "MAUREEN OLOVO CHIGOZIE", "", "F", "", "", "UTAKO FM", "CLEANER", "16-Mar-26", "", ""],
  ["CL", "14", "JOSEPH EBURU USHIE", "14-Apr-80", "F", "CROSS RIVER", "", "UTAKO FM", "CLEANER", "2-Apr-26", "", ""],

  // ================= CLAMPERS =================
  ["CM", "1", "ABDUL BELEME", "12-Jul-99", "M", "GOMBE", "", "WUSE", "CLAMPER", "3-Jan-23", "", ""],
  ["CM", "2", "ADAMU USMAN", "", "M", "", "", "WUSE", "CLAMPER", "", "", ""],
  ["CM", "3", "ALI DANIEL ABUTU", "25-Apr-73", "M", "BENUE", "", "WUSE", "CLAMPER", "11-Jul-11", "", ""],
  ["CM", "4", "GBENGA ODEGEMO", "26-Feb-76", "M", "OGUN", "", "WUSE", "CLAMPER", "27-Sep-06", "", ""],
  ["CM", "5", "IBRAHIM UMAR TANKO", "1-Jan-98", "M", "NASARAWA", "", "WUSE", "CLAMPER", "1-Nov-23", "", ""],
  ["CM", "6", "ISYAKU HARUNA", "22-Jun-94", "M", "KATSINA", "", "WUSE", "CLAMPER", "9-Jan-23", "", ""]
];
